# FriendlyChat

use_frameworks!

pod 'Firebase/Storage'
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/RemoteConfig'
pod 'Firebase/auth'
pod 'FirebaseUI'

target 'FriendlyChatSwift' do
end
